package com.ean.wsapi.hotel.v3;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-03-09T15:16:16.371+01:00
 * Generated source version: 2.7.3
 * 
 */
@WebServiceClient(name = "HotelServicesImplService", 
                  wsdlLocation = "http://api.ean.com/ean-services/ws/hotel/v3?wsdl&apiKey=ss47997prvcm58rtyrc9que4",
                  targetNamespace = "http://v3.hotel.wsapi.ean.com/") 
public class HotelServicesImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://v3.hotel.wsapi.ean.com/", "HotelServicesImplService");
    public final static QName HotelServicesImplPort = new QName("http://v3.hotel.wsapi.ean.com/", "HotelServicesImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://api.ean.com/ean-services/ws/hotel/v3?wsdl&apiKey=ss47997prvcm58rtyrc9que4");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HotelServicesImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://api.ean.com/ean-services/ws/hotel/v3?wsdl&apiKey=ss47997prvcm58rtyrc9que4");
        }
        WSDL_LOCATION = url;
    }

    public HotelServicesImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HotelServicesImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HotelServicesImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HotelServicesImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HotelServicesImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public HotelServicesImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns HotelServices
     */
    @WebEndpoint(name = "HotelServicesImplPort")
    public HotelServices getHotelServicesImplPort() {
        return super.getPort(HotelServicesImplPort, HotelServices.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HotelServices
     */
    @WebEndpoint(name = "HotelServicesImplPort")
    public HotelServices getHotelServicesImplPort(WebServiceFeature... features) {
        return super.getPort(HotelServicesImplPort, HotelServices.class, features);
    }

}
